version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: python-api

    ports:
      - "8000:8000"

    volumes:
      - ./:/app

    env_file:
      - .env

    depends_on:
      - postgres
      - redis

    restart: unless-stopped

    networks:
      - backend

  postgres:
    image: postgres:16-alpine

    container_name: postgres-db

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dashboard

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

    networks:
      - backend

  redis:
    image: redis:7-alpine

    container_name: redis-cache

    restart: unless-stopped

    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
