```dockerfile
# ============================================
# BUILDER
# ============================================
FROM python:3.12-alpine AS builder

WORKDIR /app

# Dependencias sistema
RUN apk add --no-cache \
    build-base \
    gcc \
    musl-dev \
    libffi-dev \
    openssl-dev \
    cargo

# Virtualenv
RUN python -m venv /opt/venv

# Activar venv
ENV PATH="/opt/venv/bin:$PATH"

# Copiar requirements
COPY requirements.txt .

# Instalar dependencias
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# ============================================
# RUNTIME
# ============================================
FROM python:3.12-alpine

WORKDIR /app

# Dependencias runtime
RUN apk add --no-cache \
    libstdc++ \
    libffi \
    openssl

# Copiar virtualenv
COPY --from=builder /opt/venv /opt/venv

# ACTIVAR VENV
ENV PATH="/opt/venv/bin:$PATH"

# Copiar proyecto
COPY . .

# Usuario seguro
RUN adduser -D appuser
RUN chown -R appuser:appuser /app

USER appuser

EXPOSE 8501

# Streamlit
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
```
